**After this assignment you will:**
- Be able to use iPython Notebooks
- Be able to use numpy functions and numpy matrix/vector operations
- Understand the concept of "broadcasting"
- Be able to vectorize code

## 1 - Building basic functions with numpy
### 1.1 - sigmoid function, np.exp()

In [1]:
import math
def basic_sigmoid(x):
    """
    Compute sigmoid of x
    ================================================================
    Arguments
    x : A scalar
    ================================================================
    Return
    s -- sigmoid of x
    """
    
    s = 1 / (1 + math.exp(-x))
    return s

In [2]:
# Test
basic_sigmoid(3)

0.9525741268224334

In [3]:
# use numpy instead of math
import numpy as np
x = np.array([1,2,3])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [4]:
# numpy sigmoid
import numpy as np
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [5]:
# Test
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

### 1.2 - Sigmoid gradient

In [6]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s * (1 - s)
    return ds

In [9]:
# Test
x = np.array([1,2,3])
print("sigmoid_derivative = " + str(sigmoid_derivative(x)))

sigmoid_derivative = [0.19661193 0.10499359 0.04517666]


### 1.3 - Reshaping arrays
<code>np.shape</code> and <code>np.reshape()</code>

In [16]:
def image2vector(image):
    """
    takes an input of shape and returns a vector of shape
    ================================================================
    Arguments
    image : a numpy array of shape (length, height, depth)
    ================================================================
    Return
    v : a vector of shape (length*height*depth, 1)
    """    
    
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
    return v

In [17]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


### 1.4 - Normalizing rows

In [22]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x
    ================================================================
    Arguments
    x : A numpy matrix of shape (n, m)
    ================================================================
    Return
    x : The normalized numpy matrix (by row)
    """
    
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x / x_norm
    return x

In [23]:
x = np.array([[0, 3, 4],[1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


### 1.5 - Broadcasting and the softmax function

In [25]:
def softmax(x):
    """
    Calculates the softmax for each row of the input x
    ==============================================================
    Arguments
    x - a numpy matrix of shape (m,n)
    ==============================================================
    Returns
    s : A numpy matrix of softmax of x
    """
    
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / x_sum
    return s    

In [26]:
x = np.array([[9, 2, 5, 0, 0],[7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


## 2 - Vectorization
<code>np.dot</code> and <code>np.multiply</code>